# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# some aliases for git
alias ga="git add"
alias gb="git branch"
alias gc="git checkout"
alias gca="git commit --amend"
alias gcb="git checkout -b"
alias gcm="git commit -m \"rebase me\""
alias gd="git diff"
alias gdc="git rev-list --left-right --count master...@"
alias gpl="git pull"
alias gps="git push"
alias gr="git rebase"
alias gri="git rebase -i"
alias grv="git remote -v"
alias gs="git status"

# some aliases for tmux
alias tm="tmux"
alias tma="tmux a"
alias tml="tmux ls"
alias tmk="tmux kill-session"
alias tmt="tmux a -t"